version: 2

models:
  - name: int_orders_with_payments
    description: "Ce modèle enrichit chaque commande avec le nombre total de paiements et le montant total payé."
    columns:
      - name: order_id
        description: "Identifiant unique de la commande, provenant de la table des ordres."
      - name: customer_id
        description: "Identifiant du client ayant passé la commande."
      - name: order_date
        description: "Date à laquelle la commande a été passée."
      - name: status
        description: "Statut actuel de la commande (ex : 'placed', 'shipped')."
      - name: payment_count
        description: "Nombre total de paiements effectués pour cette commande."
      - name: total_amount
        description: "Montant total payé pour cette commande, en additionnant tous les paiements."
